import type { RecordingExchange, RecordingSession } from "./recording";

type Report = RecordingSession & {
  network?: Array<RecordingExchange & { curl?: string }>;
};

export function reportHtml(report: Report): string {
  const data = JSON.stringify(report)
    .replace(/</g, "\\u003c")
    .replace(/&/g, "\\u0026");
  return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Easy Sniff · Bug replay</title><style>
*{box-sizing:border-box}body{margin:0;background:#121617;color:#e0e6df;font:14px system-ui,sans-serif}header{padding:28px 4vw;border-bottom:1px solid #303a34}h1{font-size:25px;margin:6px 0}p{color:#9dab9f}main{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(320px,1fr);gap:24px;padding:24px 4vw}.video{position:sticky;top:24px;align-self:start}video{width:100%;background:#050606;border:1px solid #364037;border-radius:8px}.timeline{position:relative;height:42px;background:#253029;border-radius:5px;margin-top:16px}.tick{position:absolute;top:0;width:3px;height:100%;background:#b9d893;cursor:pointer}.tick.error{background:#f17e75;width:5px}.tick.warning{background:#e4b96b}.cursor{position:absolute;top:0;height:100%;width:2px;background:#fff;pointer-events:none}.filters{display:flex;gap:6px;margin-bottom:12px;flex-wrap:wrap}.filters button,.details-button,.copy-button{background:#222c25;color:#cdd9cc;border:1px solid #3a4a3e;padding:8px 12px;border-radius:5px;cursor:pointer}.filters button.active{background:#bddf9f;color:#152019}.events{max-height:calc(100vh - 175px);overflow:auto}.item{display:grid;grid-template-columns:minmax(0,1fr) auto;border-bottom:1px solid #303c33}.event{width:100%;text-align:left;background:#1a211c;border:0;padding:12px;color:#dfe7dd;cursor:pointer;overflow-wrap:anywhere}.event.error{border-left:3px solid #f17e75}.event.warning{border-left:3px solid #e4b96b}.event:hover{background:#29372b}.event small{display:block;color:#9daa9d;margin-top:5px;overflow-wrap:anywhere}.time{color:#bddd9d;font-variant-numeric:tabular-nums;margin-right:10px}.details-button{align-self:center;margin:0 8px;font-size:11px}.details{grid-column:1/-1;background:#151e17;padding:16px;border-top:1px solid #405442;min-width:0}.details-title{display:flex;justify-content:space-between;gap:14px;align-items:start}.details-title strong{overflow-wrap:anywhere;font:12px/1.5 monospace}.detail-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}h3{font-size:12px;color:#bdda9e;margin:16px 0 6px}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:300px;overflow:auto;background:#1a261d;border:1px solid #334636;border-radius:4px;padding:12px;font:11px/1.5 monospace}.sensitive{border:1px solid #6b5b3c;background:#2a241b;color:#e6c89a;padding:9px 12px;border-radius:5px;margin-top:12px}@media(max-width:900px){main{grid-template-columns:1fr}.video{position:static}.events{max-height:none}.detail-grid{grid-template-columns:1fr}}
  </style></head><body><header><small>Easy Sniff / BUG REPLAY</small><h1 id="title"></h1><p id="meta"></p><p>Local report. Review the video and request details before sharing.</p><p id="sensitive" class="sensitive" hidden>This report contains full HTTP details, including tokens and cookies. Share it only with trusted developers.</p></header><main><section class="video"><video id="video" controls preload="metadata" src="video.webm"></video><div id="timeline" class="timeline"><span class="cursor" id="cursor"></span></div><p>Click a timeline mark or event to jump to that moment.</p></section><section><div id="filters" class="filters"></div><div id="events" class="events"></div></section></main><script id="report" type="application/json">${data}</script><script>
const data=JSON.parse(document.getElementById('report').textContent),video=document.getElementById('video'),events=document.getElementById('events'),timeline=document.getElementById('timeline'),filters=document.getElementById('filters');
const network=new Map((data.network||[]).map(item=>[item.id,item]));
document.getElementById('title').textContent=data.title;document.getElementById('meta').textContent=new Date(data.startedAt).toLocaleString()+' · '+Math.round(((data.endedAt||data.startedAt)-data.startedAt)/1000)+' s · '+data.events.length+' events · '+data.tabUrl;
document.getElementById('sensitive').hidden=!data.fullHttp;
const duration=Math.max(1,(data.endedAt-data.startedAt)||1);let filter='all';const fmt=ms=>(ms/1000).toFixed(1)+'s';
function seek(ms){const end=Number.isFinite(video.duration)?video.duration:duration/1000;video.currentTime=Math.min(ms/1000,Math.max(0,end-.01));video.play().catch(()=>{});}
function line(parent,label,value){const title=document.createElement('h3'),body=document.createElement('pre');title.textContent=label;body.textContent=value==null?'—':typeof value==='string'?value:JSON.stringify(value,null,2);parent.append(title,body);}
function bodyText(body){return body?(body.base64?'[base64] ':'')+(body.content||body.error||'—')+(body.truncated?'\\n[truncated]':''):'—';}
function showDetails(parent,exchange){const panel=document.createElement('div');panel.className='details';panel.hidden=true;const heading=document.createElement('div');heading.className='details-title';const name=document.createElement('strong');name.textContent=exchange.method+' '+exchange.url;const copy=document.createElement('button');copy.className='copy-button';copy.textContent='Copy cURL';copy.onclick=async()=>{try{await navigator.clipboard.writeText(exchange.curl||'');copy.textContent='Copied';setTimeout(()=>copy.textContent='Copy cURL',1600)}catch{prompt('Copy cURL',exchange.curl||'')}};heading.append(name,copy);panel.append(heading);line(panel,'Status / type / duration / protocol / address',[exchange.status,exchange.resourceType,exchange.duration,exchange.protocol,exchange.remoteAddress]);const grid=document.createElement('div');grid.className='detail-grid';const request=document.createElement('section'),response=document.createElement('section');line(request,'Request headers',exchange.requestHeadersText||exchange.requestHeaders);line(request,'Request cookies',exchange.requestCookies||[]);line(request,'Request body',bodyText(exchange.requestBody));line(response,'Response headers',exchange.responseHeadersText||exchange.responseHeaders||{});line(response,'Blocked Set-Cookie',exchange.responseCookies||[]);line(response,'Response body',bodyText(exchange.responseBody));line(response,'Network details',{statusText:exchange.statusText,fromDiskCache:exchange.fromDiskCache,encodedDataLength:exchange.encodedDataLength,timing:exchange.timing,error:exchange.error});grid.append(request,response);panel.append(grid);parent.append(panel);return panel;}
function render(){events.replaceChildren();filters.replaceChildren();timeline.querySelectorAll('.tick').forEach(x=>x.remove());for(const type of ['all','errors','network','console','markers']){const b=document.createElement('button');b.textContent=type;b.className=filter===type?'active':'';b.onclick=()=>{filter=type;render()};filters.append(b)}
for(const event of data.events){const match=filter==='all'||filter==='errors'&&event.severity==='error'||filter==='network'&&['request','response','network-error','websocket'].includes(event.kind)||filter==='console'&&['console','exception'].includes(event.kind)||filter==='markers'&&event.kind==='marker';if(!match)continue;const item=document.createElement('div');item.className='item';const row=document.createElement('button');row.className='event '+event.severity;const top=document.createElement('span');top.className='time';top.textContent=fmt(event.at);row.append(top,document.createTextNode(event.title));if(event.detail){const small=document.createElement('small');small.textContent=event.detail;row.append(small)}row.onclick=()=>seek(event.at);item.append(row);const exchange=network.get(event.exchangeId);if(exchange){const toggle=document.createElement('button');toggle.className='details-button';toggle.textContent='Details';const panel=showDetails(item,exchange);toggle.onclick=()=>{panel.hidden=!panel.hidden;toggle.textContent=panel.hidden?'Details':'Hide details'};item.append(toggle)}events.append(item);if(event.severity!=='normal'||event.kind==='marker'){const tick=document.createElement('button');tick.className='tick '+event.severity;tick.style.left=Math.min(99.5,100*event.at/duration)+'%';tick.title=fmt(event.at)+' · '+event.title;tick.onclick=()=>seek(event.at);timeline.append(tick)}}}
render();video.addEventListener('loadedmetadata',()=>{if(!Number.isFinite(video.duration)){video.currentTime=1e10;video.addEventListener('seeked',()=>{video.currentTime=0},{once:true})}});video.ontimeupdate=()=>{document.getElementById('cursor').style.left=Math.min(100,video.currentTime*1000/duration)+'%'};
  </script></body></html>`;
}
